services:
  - type: web
    name: hospital-core
    env: docker
    rootDir: core-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: "2"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"

  - type: web
    name: hospital-appointment
    env: docker
    rootDir: appointment-service
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: "2"
      - key: EUREKA_SERVER_HOSTPORT
        fromService:
          name: hospital-core
          type: web
          property: hostport
